### ISSUE TITLE
Deprecate vimdriver and lifecycle driver commands in LMCTL in favour of a new resourcedriver command

### ISSUE THREAD

**Issue by sglover** [accanto-systems/lmctl#45]
LM is replacing the distinction between VIM and LifecycleDrivers with a single type "Resource Driver". A new resourcedriver command should be created to support onboarding a Resource driver. 

The current vimdriver and lifecycledriver commands should be deprecated. When used they should display a warning message but then forward to the resourcedriver command on behalf of the user.

**Comment by dvaccarosenna** [comment]
Fixed by #48

**Comment by dvaccarosenna** [comment]
Note: `vimdriver` and `lifecycle` commands have been restored to maintain support for LM 2.1
